export const actions = {
  UPDATE_APPROVED: "UPDATE_APPROVED",
  UPDATE_APPROVED_SUCCESS: "UPDATE_APPROVED_SUCCESS",
  UPDATE_APPROVED_FAILURE: "UPDATE_APPROVED_FAILURE",

  REJECT_APPROVED: "REJECT_APPROVED",
  REJECT_APPROVED_SUCCESS: "REJECT_APPROVED_SUCCESS",
  REJECT_APPROVED_FAILURE: "REJECT_APPROVED_FAILURE",
  
  INVITE_REVIEWER: "INVITE_REVIEWER",
  INVITE_REVIEWER_SUCCESS: "INVITE_REVIEWER_SUCCESS",
  INVITE_REVIEWER_FAILURE: "INVITE_REVIEWER_FAILURE",
};

export default actions;
