export const actions = {
  UPDATE_APPROVED: "UPDATE_APPROVED",
  UPDATE_APPROVED_SUCCESS: "UPDATE_APPROVED_SUCCESS",
  UPDATE_APPROVED_FAILURE: "UPDATE_APPROVED_FAILURE",

  REJECT_APPROVED: "REJECT_APPROVED",
  REJECT_APPROVED_SUCCESS: "REJECT_APPROVED_SUCCESS",
  REJECT_APPROVED_FAILURE: "REJECT_APPROVED_FAILURE",
};

export default actions;
