export const actions = {
  GET_CONTACTS: "GET_CONTACTS",
  GET_CONTACTS_SUCCESS: "GET_CONTACTS_SUCCESS",
  GET_CONTACTS_FAILURE: "GET_CONTACTS_FAILURE",

  ADD_CONTACT: "ADD_CONTACT",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",

  EDIT_CONTACT: "EDIT_CONTACT",
  EDIT_CONTACT_SUCCESS: "EDIT_CONTACT_SUCCESS",
  EDIT_CONTACT_FAILURE: "EDIT_CONTACT_FAILURE",
};

export default actions;
