export const actions = {
  GET_STATUS: "GET_STATUS",
  GET_STATUS_SUCCESS: "GET_STATUS_SUCCESS",
  GET_STATUS_FAILURE: "GET_STATUS_FAILURE",

  UPDATE_STATUS: "UPDATE_STATUS",
  UPDATE_STATUS_SUCCESS: "UPDATE_STATUS_SUCCESS",
  UPDATE_STATUS_FAILURE: "UPDATE_STATUS_FAILURE",
};

export default actions;
