export const actions = {
  GET_ADDRESSES: "GET_ADDRESSES",
  GET_ADDRESSES_SUCCESS: "GET_ADDRESSES_SUCCESS",
  GET_ADDRESSES_FAILURE: "GET_ADDRESSES_FAILURE",

  ADD_ADDRESS: "ADD_ADDRESS",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",

  EDIT_ADDRESS: "EDIT_ADDRESS",
  EDIT_ADDRESS_SUCCESS: "EDIT_ADDRESS_SUCCESS",
  EDIT_ADDRESS_FAILURE: "EDIT_ADDRESS_FAILURE",

  DELETE_ADDRESS: "DELETE_ADDRESS",
  DELETE_ADDRESS_SUCCESS: "DELETE_ADDRESS_SUCCESS",
  DELETE_ADDRESS_FAILURE: "DELETE_ADDRESS_FAILURE",
};

export default actions;
