export const actions = {
  GET_REVISIONS: "GET_REVISIONS",
  GET_REVISIONS_SUCCESS: "GET_REVISIONS_SUCCESS",
  GET_REVISIONS_FAILURE: "GET_REVISIONS_FAILURE",
  UPDATE_PARTITIONVERFICATIONSTATE: "UPDATE_PARTITIONVERFICATIONSTATE",
  UPDATE_PARTITIONVERFICATIONSTATE_SUCCESS: "UPDATE_PARTITIONVERFICATIONSTATE_SUCCESS",
  UPDATE_PARTITIONVERFICATIONSTATE_FAILURE: "UPDATE_PARTITIONVERFICATIONSTATE_FAILURE",
};

export default actions;
