export const actions = {
  GET_FILES: "GET_FILES",
  GET_FILES_SUCCESS: "GET_FILES_SUCCESS",
  GET_FILES_FAILURE: "GET_FILES_FAILURE",

  ADD_FILES: "ADD_FILES",
  ADD_FILES_SUCCESS: "ADD_FILES_SUCCESS",
  ADD_FILES_FAILURE: "ADD_FILES_FAILURE",

  UPDATE_NAME: "UPDATE_NAME",
  UPDATE_NAME_SUCCESS: "UPDATE_NAME_SUCCESS",
  UPDATE_NAME_FAILURE: "UPDATE_NAME_FAILURE",

  REMOVE_FILE: "REMOVE_FILE",
  REMOVE_FILE_SUCCESS: "REMOVE_FILE_SUCCESS",
  REMOVE_FILE_FAILURE: "REMOVE_FILE_FAILURE",

  GET_REVISIONS: "GET_REVISIONS",
  GET_REVISIONS_SUCCESS: "GET_REVISIONS_SUCCESS",
  GET_REVISIONS_FAILURE: "GET_REVISIONS_FAILURE",
};

export default actions;
