export const actions = {
  GET_FILES: "GET_FILES",
  GET_FILES_SUCCESS: "GET_FILES_SUCCESS",
  GET_FILES_FAILURE: "GET_FILES_FAILURE",

  ADD_FILES: "ADD_FILES",
  ADD_FILES_SUCCESS: "ADD_FILES_SUCCESS",
  ADD_FILES_FAILURE: "ADD_FILES_FAILURE",

  UPDATE_STATUS: "UPDATE_STATUS",
  UPDATE_STATUS_SUCCESS: "UPDATE_STATUS_SUCCESS",
  UPDATE_STATUS_FAILURE: "UPDATE_STATUS_FAILURE",
};

export default actions;
