export const actions = {
  ADD_COMMENTS: "ADD_COMMENTS",
  ADD_COMMENTS_SUCCESS: "ADD_COMMENTS_SUCCESS",
  ADD_COMMENTS_FAILURE: "ADD_COMMENTS_FAILURE",

  GET_COMMENTS: "GET_COMMENTS",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
  GET_COMMENTS_FAILURE: "GET_COMMENTS_FAILURE",

  GET_PARTITIONCOMMENTS: "GET_PARTITIONCOMMENTS",
  GET_PARTITIONCOMMENTS_SUCCESS: "GET_PARTITIONCOMMENTS_SUCCESS",
  GET_PARTITIONCOMMENTS_FAILURE: "GET_PARTITIONCOMMENTS_FAILURE",
};

export default actions;
