export const actions = {
  GET_SAMPLES: "GET_SAMPLES",
  GET_SAMPLES_SUCCESS: "GET_SAMPLES_SUCCESS",
  GET_SAMPLES_FAILURE: "GET_SAMPLES_FAILURE",

  ADD_SAMPLES: "ADD_SAMPLES",
  ADD_SAMPLES_SUCCESS: "ADD_SAMPLES_SUCCESS",
  ADD_SAMPLES_FAILURE: "ADD_SAMPLES_FAILURE",
};

export default actions;
